### ISSUE TITLE
No icons in toolbar

### ISSUE THREAD

**Issue by daciwei** [lxqt/lxqt-archiver#174] opened 2020-06-30 21:13 UTC
lxqt-archiver has no icons in toolbar.

![x2](https://user-images.githubusercontent.com/13871989/86177177-d7b3dc80-bb2e-11ea-87ed-1fb0db117e63.png)

##### System Information
* Distribution & Version: Arch Linux 
* Kernel: 5.7.6-arch1-1 
* DM: dwm-6.2 
* Package version: lxqt-archiver 0.2.0

```
$ yay lxqt | grep Installed
42 aur/breeze-lxqt 1.4-1 (+15 0.00) (Installed)
22 community/qterminal 0.15.0-1 (222.4 KiB 932.6 KiB) [lxqt] (Installed)
21 community/pcmanfm-qt 0.15.1-1 (345.5 KiB 1.7 MiB) [lxqt] (Installed)
18 community/lxqt-themes 0.15.0-1 (3.1 MiB 3.6 MiB) [lxqt] (Installed)
5 community/lxqt-archiver 0.2.0-1 (200.6 KiB 784.5 KiB) [lxqt] (Installed)
2 community/lximage-qt 0.15.0-1 (158.4 KiB 664.5 KiB) [lxqt] (Installed)

$ yay icon | grep Installed
33 community/lxqt-themes 0.15.0-1 (3.1 MiB 3.6 MiB) [lxqt] (Installed)
7 extra/hicolor-icon-theme 0.17-2 (10.2 KiB 54.2 KiB) (Installed)
6 extra/gtk-update-icon-cache 1:3.24.21-1 (15.3 KiB 38.7 KiB) (Installed)
1 extra/adwaita-icon-theme 3.36.1-1 (10.7 MiB 22.3 MiB) (Installed)

$ yay theme | grep Installed
53 community/lxqt-themes 0.15.0-1 (3.1 MiB 3.6 MiB) [lxqt] (Installed)
50 community/lxappearance 0.6.3-2 (80.1 KiB 405.0 KiB) [lxde] (Installed)
43 community/gtk-chtheme 0.3.1-9 (10.8 KiB 35.0 KiB) (Installed)
22 extra/sound-theme-freedesktop 0.8-4 (370.0 KiB 461.2 KiB) (Installed)
15 extra/libcanberra 0.30+2+gc0620e4-3 (83.8 KiB 403.3 KiB) (Installed)
12 extra/hicolor-icon-theme 0.17-2 (10.2 KiB 54.2 KiB) (Installed)
11 extra/gtk-engines 2.21.0-5 (266.0 KiB 1.2 MiB) (Installed)
8 extra/gnome-themes-extra 3.28-2 (2.5 MiB 4.4 MiB) [gnome] (Installed)
4 extra/breeze-gtk 5.19.2-1 (237.6 KiB 7.4 MiB) [plasma] (Installed)
1 extra/adwaita-icon-theme 3.36.1-1 (10.7 MiB 22.3 MiB) (Installed)

$ yay qt5 | grep Installed
69 extra/qt5-x11extras 5.15.0-1 (14.5 KiB 40.6 KiB) [qt qt5] (Installed)
66 extra/qt5-webkit 5.212.0alpha4-6 (12.2 MiB 46.7 MiB) (Installed)
64 extra/qt5-webengine 5.15.0-2 (44.1 MiB 144.7 MiB) [qt qt5] (Installed)
63 extra/qt5-webchannel 5.15.0-1 (72.5 KiB 222.9 KiB) [qt qt5] (Installed)
58 extra/qt5-svg 5.15.0-1 (146.0 KiB 490.4 KiB) [qt qt5] (Installed)
54 extra/qt5-sensors 5.15.0-1 (177.1 KiB 908.8 KiB) [qt qt5] (Installed)
41 extra/qt5-location 5.15.0-1 (2.9 MiB 11.0 MiB) [qt qt5] (Installed)
40 extra/qt5-imageformats 5.15.0-1 (52.7 KiB 208.1 KiB) [qt qt5] (Installed)
35 extra/qt5-declarative 5.15.0-1 (4.8 MiB 24.7 MiB) [qt qt5] (Installed)
31 extra/qt5-base 5.15.0-3 (12.9 MiB 64.1 MiB) [qt qt5] (Installed)
15 extra/poppler-qt5 0.88.0-1 (187.7 KiB 666.0 KiB) (Installed)
6 extra/libdbusmenu-qt5 0.9.3+16.04.20160218-5 (159.2 KiB 600.9 KiB) (Installed)
2 extra/avahi 0.8+15+ge8a3dd0-1 (435.9 KiB 1.8 MiB) (Installed)


```

**Comment by tsujan** [comment] 2020-06-30 23:41
Some of the icons are in `breeze-icons`; so, you need that package (or a good icon set that provides those icons). However, your  screenshot shows that your problem is more fundamental: Since `libqtxdg`, `liblxqt`, `lxqt-qtplugin`, `lxqt-config` and `lxqt-session` aren't in your lists, you can't be inside an LXQt session. Perhaps, you're inside a GTK-based session, in which case you need a Qt configuration tool like `qt5ct` (or, instead, you could install the above-mentioned packages and set the environment variable `QT_QPA_PLATFORMTHEME` to` lxqt`).

Anyway, this was rather a Qt/Arch question, not a bug report about lxqt-archiver; hence closing...

**Closed by tsujan** 2020-06-30 23:41 UTC
