### ISSUE TITLE
Drag-and-drop support

### ISSUE THREAD

**Issue by Ilya87** [lxqt/lxqt-archiver#79] opened 2019-03-03 23:41 UTC
##### Steps to Reproduce (for bugs)

1. Drag files or folder from archive using lxqt-archiver
2. Try to drop them to file manager's window 
3. No files from archive are extracted
Implementing drag-and-drop will make decompressing much more easy.

##### System Information

* Distribution & Version: Antergos x86_64
* Kernel: 4.20.13-arch1-1-ARCH
* Qt Version: 5.12
* libqtxdg Version: 3.3.1
* lxqt-build-tools Version: 0.6
* Package version: g941f586

**Comment by tsujan** [comment] 2019-03-04 14:48
The logic of implementation will be easy but it needs to be done after https://github.com/lxqt/lxqt-archiver/pull/80 is merged.

**Comment by tsujan** [comment] 2019-03-04 18:14
OK, I was wrong; the logic is not simple. It would be simple if the extraction of the dragged item happened before dropping but that either interferes with DND or requires dropping only after the extraction is finished. Neither is good.

However, the solution may be what PCMan has done in libfm-qt -- it needs X11 dependency.

**Comment by tsujan** [comment] 2019-03-04 21:22
OK, the details of the problem:

File DND from lxqt-archiver *to anywhere possible* can be easily implemented but the dragged file can be dropped only after its extraction is finished. Therefore, with huge archives, there may be a considerable interval between dragging and dropping: even if the user clicks somewhere after dragging a file from lxqt-archiver, the cursor will change its shape to `Qt::DragCopyCursor` (= ready to drop) only after the file is extracted (in `/tmp`).

Suppose that you drag a file from a really big archive and then, you do another job -- text editing, for example -- and then, suddenly, the cursor changes its shape, announcing that a file can be dropped. You could drop the extracted file in another place but the whole scenario looks a little weird. (Actually, that's what I've done in Arqiver.)

file-roller/engrampa starts to extract the file *after dropping* but I haven't found a Qt method for that yet.

Ark only drops files inside KDE apps like Dolphin. That's not what we want for lxqt-archiver.

I remove my self-assignment to let others work on DND *to anywhere possible* if they want.

**Comment by Ilya87** [comment] 2019-03-04 22:59
Maybe there is another solution - when I drag and drop files & folders from archive lxqt opens default extract window (or simplified one) with radio button "selected" checked, where the path of extraction get from the path of window of dropping, so the user should only click on ok button or change some extraction options.
![screenshot-80717503](https://user-images.githubusercontent.com/1446573/53768570-4dcc1300-3eea-11e9-89b2-774b50a6cce3.png)

**Comment by tsujan** [comment] 2019-03-04 23:17
@Ilya87 The problem is that we can't know the drop destination with purely Qt methods. `QPlatformDrag` takes care of dropping by using private Qt headers. Moreover, dropping can happen anywhere, not necessary inside a Qt app (let alone inside our `Fm::FolderView`).

 `QPlatformDrag` makes a nice DND outside the app to anywhere but, for an archive manager, the drop should wait for the extraction to be finished -- not important with ordinary archives but the user should wait with huge ones.

**Comment by tsujan** [comment] 2019-03-05 00:37
This screencast shows what I said: https://www.dropbox.com/s/kjnm13kor4ky7c1/extraction.mkv?dl=0

Here, a 44-MiB Qt source archive is opened. The first time, it takes a while until the drop becomes ready but, the second time, the drop is instantaneous because the selected files/folders are already extracted (into `/tmp`, usually on RAM).

**Comment by tsujan** [comment] 2019-05-04 11:15
OK, it seems to me that there's no other way. Will make a PR after my previous PRs are merged (because of conflicts).

**Closed** 2019-07-21 11:31 UTC
Labels: enhancement
